### PR TITLE
edit the developer guide for v1.2

### PR DESCRIPTION
**Pull request by ZZG229**
edit the developer guide to include implementation for feature 'diagnosis'

### CODE REVIEW

**Comment by kumuwu** [comment]
okay 💯

**Comment by shuiherng** [comment]
Thanks! Nice job

**Comment by lixinze777** [comment]
Well done!

**Comment by ZZG229** [comment]
merge developer guide with shui herng's part

**Comment by ZZG229** [comment]
merge with main repo

**Pull request merged**
